const data = [
    {_id:"1", 
    item:"PIZZA1",
    heading:"Special title treatment",
    text:"eat this special pizza at special price",
    image:"http://trumpwallpapers.com/wp-content/uploads/Pizza-Wallpaper-37-2560-x-1600.jpg",
    price:199,
    },
    {_id:"2", 
    item:"PIZZA2",
    heading:"Special title treatment",
    text:"eat this special pizza at special price",
    image:"https://images2.alphacoders.com/970/thumb-1920-97040.jpg",
    price:299,
    },
    {_id:"3", 
    item:"PIZZA3",
    heading:"Special title treatment",
    text:"eat this special pizza at special price",
    image:"https://thelevelbrighton.org.uk/wp-content/uploads/2016/03/Pizza-PriceGuideLady.co_.uk_.jpg",
    price:99,
    },
    {_id:"4", 
    item:"PIZZA4",
    heading:"Special title treatment",
    text:"eat this special pizza at special price",
    image:"https://c4.wallpaperflare.com/wallpaper/234/543/684/food-pizza-wallpaper-preview.jpg",
    price:399,
    },
    {_id:"5", 
    item:"Burger",
    heading:"Special title treatment",
    text:"eat this special pizza at special price",
    image:"https://images.unsplash.com/photo-1571091718767-18b5b1457add?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Nnx8YnVyZ2VyfGVufDB8fDB8&ixlib=rb-1.2.1&w=1000&q=80",
    price:199,
    },
    {_id:"6", 
    item:"Burger2",
    heading:"Special title treatment",
    text:"eat this special pizza at special price",
    "image":"https://c4.wallpaperflare.com/wallpaper/209/721/107/food-burger-wallpaper-preview.jpg",
    price:99,
    },
    {_id:"7", 
    item:"BURGER3",
    heading:"Special title treatment",
    text:"eat this special pizza at special price",
    image:"https://images2.alphacoders.com/276/thumb-350-276352.jpg",
    price:189,
    },
    {_id:"8", 
    item:"BURGER4",
    heading:"Special title treatment",
    text:"eat this special pizza at special price",
    image:"https://wallpaperaccess.com/full/2004521.jpg",
    price:179,
    },
    {_id:"9", 
    item:"STARTER1",
    heading:"Special title treatment",
    text:"eat this special pizza at special price",
    image:"http://www.dineout.co.in/blog/wp-content/uploads/2018/05/shutterstock_753500476-1-700x467.jpg",
    price:189,
    },
    {_id:"10", 
    item:"STARTER2",
    heading:"Special title treatment",
    text:"eat this special pizza at special price",
    image:"https://c.ndtvimg.com/2020-04/6vslovro_kebab_625x300_15_April_20.jpg",
    price:159,
    },
    {_id:"11", 
    item:"STARTER3",
    heading:"Special title treatment",
    text:"eat this special pizza at special price",
    image:"https://justtadka.com/images/product/CHICKEN%20LOLIPOP.jpg",
    price:149,
    },
    {_id:"12", 
    item:"STARTER4",
    heading:"Special title treatment",
    text:"eat this special pizza at special price",
    image:"https://i.ytimg.com/vi/EpR4Ie0DR3I/maxresdefault.jpg",
    price:139,
    },
]

export default data;